List/room granularity for the receipts extension
matrix-org/sliding-sync pull request #54
Opened 2023-04-03 12:58 UTC by DMRobertson

Part of #41. Based on #53.

2023-04-03 16:58 UTC, kegsay requested changes
A few things about tests, but LGTM otherwise.

2023-04-03 16:58 UTC, kegsay commented on testutils/m/match.go
> +func LogResponse(t *testing.T) RespMatcher {
Fancy, I like it!

2023-04-03 16:58 UTC, kegsay commented on tests-e2e/receipts_test.go
> +	room4 := alice.CreateRoom(t, map[string]interface{}{"preset": "public_chat", "name": "room 2"})
```suggestion
	room4 := alice.CreateRoom(t, map[string]interface{}{"preset": "public_chat", "name": "room 4"})
```

2023-04-03 16:58 UTC, kegsay commented on tests-e2e/receipts_test.go
> +	room3 := alice.CreateRoom(t, map[string]interface{}{"preset": "public_chat", "name": "room 1"})
```suggestion
	room3 := alice.CreateRoom(t, map[string]interface{}{"preset": "public_chat", "name": "room 3"})
```

2023-04-03 16:58 UTC, kegsay commented on tests-e2e/receipts_test.go
> +	message4 := alice.SendEventSynced(t, room1, messageEvent)
Presumably meant to be rooms 1-4 not room 1 all the time.

2023-04-03 16:58 UTC, kegsay commented on tests-e2e/receipts_test.go
> +	time.Sleep(300 * time.Millisecond) // TODO: find a better way to wait until the proxy has processed this.
You've not done a sliding sync request yet, so this sleep means nothing.

2023-04-03 16:58 UTC, kegsay commented on tests-e2e/receipts_test.go
> +	t.Log("Bob sees his receipt in room 4, but not in room 3.")
So testing for negation I would do what you're doing here and send room 3 BEFORE room 4. That way, you just need to test until you see room 4 and not wait an indeterminate amount of time for room 3, effectively using room 4 as a sentinel.

2023-04-03 16:58 UTC, kegsay commented on tests-e2e/receipts_test.go
> +	go bobIncrementalSync()
Same deal as the last PR, you don't need this.

2023-04-03 19:12 UTC, DMRobertson commented on tests-e2e/receipts_test.go
> +	room4 := alice.CreateRoom(t, map[string]interface{}{"preset": "public_chat", "name": "room 2"})
Ugh, forgot a `/g` when I did an `s/1/3`

2023-04-04 15:59 UTC, kegsay approved these changes

2023-04-04 16:17 UTC, merged